In [4]:
import numpy as np

In [5]:
# Function to train a fashion recommendation model
#
# purchases: a matrix where each row represents the purchases of a single customer,
#            and each column represents a different fashion item
#
# Returns a matrix of item-item similarities, where each entry (i, j) represents the similarity
# between fashion items i and j
def train_fashion_model(purchases):
  # Compute the item-item similarity matrix
  sim_matrix = purchases.T.dot(purchases)

  # Normalize the similarity matrix
  norms = np.linalg.norm(purchases, axis=0)
  sim_matrix = sim_matrix / norms / norms[:, None]

  return sim_matrix

In [6]:

# Function to make fashion recommendations
#
# sim_matrix: the item-item similarity matrix, as computed by the train_fashion_model function
# purchases: a vector of past purchases for a single customer, where each entry represents a different fashion item
# num_recs: the number of recommendations to make
#
# Returns a list of fashion item indices representing the recommended items
def recommend_fashion(sim_matrix, purchases, num_recs):
  # Compute a weighted sum of the rows of the similarity matrix,
  # where the weights are the past purchases of the customer
  rec_vector = sim_matrix.dot(purchases)

  # Sort the recommendation vector in descending order
  sorted_indices = np.argsort(rec_vector)[::-1]

  # Return the top num_recs items from the sorted recommendation vector
  return sorted_indices[:num_recs]


### Example usage:

In [7]:
# Define a matrix of past purchases, where each row represents a different customer
# and each column represents a different fashion item
purchases = np.array([[1, 1, 0, 0, 1],
                      [0, 1, 0, 0, 1],
                      [0, 0, 1, 0, 1],
                      [0, 1, 0, 1, 0],
                      [0, 1, 0, 0, 0]])

In [8]:
# Train the fashion recommendation model
sim_matrix = train_fashion_model(purchases)

In [9]:
# Make recommendations for the first customer
recs = recommend_fashion(sim_matrix, purchases[0, :], 3)
print(recs)  # Should print [1, 4, 2]

[4 1 0]


In [10]:
# Make recommendations for the second customer
recs = recommend_fashion(sim_matrix, purchases[1, :], 3)
print(recs)  # Should print [1, 4, 0]

[4 1 0]


In [11]:
# Make recommendations for the third customer
recs = recommend_fashion(sim_matrix, purchases[2, :], 3)
print(recs)  # Should print [2, 4, 1]

[4 2 1]
